### ISSUE TITLE
Cannot load underlying module for 'SwiftyJSON'

### ISSUE THREAD

**Issue by jagdeepChicmic** [sency-ai/smkit-ui-react-native-demo#10]
I can't compile the project after installing the library.
![Screenshot 2024-06-27 at 12 38 30 PM](https://github.com/sency-ai/smkit-ui-react-native-demo/assets/98816256/7d87470d-1608-4f03-b76a-083240395aba)

**Comment by ofergoldstein** [comment]
Hi @jagdeepChicmic, thanks for reporting this.
We have just merged a new commit that is resolving this issue.
