### ISSUE TITLE
 UIElement Enum Mapping Error in react-native-smkit-ui Library Causes Workout Initialization Failure

### ISSUE THREAD

**Issue by caesarkrit** [sency-ai/smkit-ui-react-native-demo#29]
Environment:
Platform: Android
React Native Version: "0.74.3"
Library Version: 0.1.6
Operating System: Windows 10

Problem:
I'm encountering an issue while using the react-native-smkit-ui library version 0.1.6 in a React Native project. Specifically, the problem arises when attempting to start a custom workout using the library's startCustomWorkout function.

The error message is as follows:
Workout error: [Error: Expected one of [Timer, RepsCounter, GaugeOfMotion, Skeleton] but was repsCounter at path $.exercises[0].uiElements[0]]
Error name: Error
Error message: Expected one of [Timer, RepsCounter, GaugeOfMotion, Skeleton] but was repsCounter at path $.exercises[0].uiElements[0]

Steps to Reproduce:

1. Set up a React Native project using react-native-smkit-ui version 0.1.6.

2. Define a workout with UIElement values in the TypeScript code as follows:
const exercise = new SMExercise(
    "Simple Exercise", 
    30, 
    5, 
    null, 
    null, 
    [UIElement.RepsCounter, UIElement.Timer], 
    "HighKnees", 
    true, 
    null, 
    new SMScoringParams(
        null, 
        0.3, 
        20, 
        10, 
        null, 
        null 
    )
);
3. Attempt to start the workout using startCustomWorkout.

Expected Behavior:
The workout should start without any errors, utilizing the specified UIElement values.

Actual Behavior:
An error occurs indicating a mismatch in the expected UIElement enum values. The error suggests that the lowercase repsCounter is received instead of the correctly cased RepsCounter.

Possible Causes:
There may be an inconsistency in how UIElement values are handled or mapped between the TypeScript and Kotlin parts of the library. It's possible that the enum values are not correctly aligned or are being transformed unexpectedly.

Changes Made to SMMapper.kt:
I made changes to SMMapper.kt to ensure non-nullable types by using default values. Here are the relevant modifications:
private fun SMKitExercise.toSMExercise(): SMExercise = SMExercise(
    prettyName = prettyName ?: "",
    exerciseIntro = exerciseIntro ?: "",
    totalSeconds = totalSeconds ?: 0, // Ensured non-null
    introSeconds = introSeconds ?: 0, // Ensured non-null
    videoInstruction = videoInstruction ?: "",
    uiElements = uiElements ?: emptySet(), // Checked for proper mapping
    detector = detector ?: "",
    repBased = repBased ?: false,
    exerciseClosure = exerciseClosure ?: "",
    scoringParams = scoringParams?.toParams() ?: ScoringParams(
        type = "",
        scoreFactor = 0f, // Ensured non-null
        targetTime = 0,   // Ensured non-null
        targetReps = 0,   // Ensured non-null
        targetRom = "",
        passCriteria = null
    )
)

private fun SMKitScoringParams.toParams(): ScoringParams {
    return ScoringParams(
        type = type ?: "",
        scoreFactor = scoreFactor ?: 0f,  // Ensured non-null
        targetTime = targetTime ?: 0,     // Ensured non-null
        targetReps = targetReps ?: 0,     // Ensured non-null
        targetRom = targetRom ?: "",
        passCriteria = passCriteria
    )
}

Possible Causes:
There may be an inconsistency in how UIElement values are handled or mapped between the TypeScript and Kotlin parts of the library. It's possible that the enum values are not correctly aligned or are being transformed unexpectedly.

**Comment by SencyCaspit** [comment]
Hi @caesarkrit, 
Thank you for reaching out and giving a very detailed information about your problem.
We recently publish new version for our RN SDK, please update your dependency to 0.1.7 in package.json.
It is recommended to clean your gradle local machine's cache before running `npm run android`.
Please feel free to let us know how things going on.

Sincerely,
Sency Dev Team.
